version: '3.7'

services:
  crawler:
    container_name: "webscrapper-chromium"
    image: 'ghcr.io/go-rod/rod'
    restart: always
    ports:
      - '7317:7317'
    networks:
      - default

  api:
    container_name: "webscrapper-api"
    depends_on:
      - postgres
      - crawler
    build: .
    restart: always
    ports:
      - 3000:3000
    volumes:
      - '.:/app'
    networks:
      - default

networks:
  default:
